In [3]:
import numpy as np

## Practice

In [85]:
mat = np.eye(5)
mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
arr = np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [87]:
arr1 = np.linspace(1,100,20)
arr1

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [88]:
mat = np.random.randint(1,26,25).reshape(5,5)
mat

array([[11,  9, 21, 21,  4],
       [24,  4,  6, 12, 14],
       [21,  4,  7, 17, 16],
       [ 2, 18, 19, 19, 12],
       [ 7,  2, 15,  5, 18]], dtype=int32)

In [89]:
mat[2:3,:]

array([[21,  4,  7, 17, 16]], dtype=int32)

In [90]:
mat[:,2:3]

array([[21],
       [ 6],
       [ 7],
       [19],
       [15]], dtype=int32)

In [91]:
mat[:3,:3]

array([[11,  9, 21],
       [24,  4,  6],
       [21,  4,  7]], dtype=int32)

In [92]:
mat[:,::2]

array([[11, 21,  4],
       [24,  6, 14],
       [21,  7, 16],
       [ 2, 19, 12],
       [ 7, 15, 18]], dtype=int32)

In [93]:
mat = np.arange(1,13).reshape(2,6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [94]:
mat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
mat.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
mat.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
a = np.arange(1,11)
b = np.arange(21,31)

In [98]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [100]:
a + b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [101]:
a - b

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [102]:
a * b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [103]:
a/b

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [104]:
a**b

array([                  1,             4194304,         94143178827,
           281474976710656,  298023223876953125, 4561031516192243712,
       5059972980857283351,                   0, 5756027422282277481,
       5076944270305263616])

In [105]:
a**1/b

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [106]:
a.mean()

np.float64(5.5)

In [107]:
np.median(b)

np.float64(25.5)

In [108]:
np.max(a)

np.int64(10)

In [109]:
np.min(b)

np.int64(21)

In [110]:
np.std(a)

np.float64(2.8722813232690143)

In [111]:
arr = np.random.randint(1,50,50)
arr

array([35, 45,  7,  2,  3, 43, 42, 43, 11,  5, 42, 13, 35,  9, 44,  1, 19,
       31, 16, 17, 33, 34, 25, 37, 35, 35, 34, 41, 29, 30, 35,  1, 15,  4,
       14, 42, 42,  4, 30, 12, 19, 49, 23, 17, 20, 41, 19, 37, 21, 23],
      dtype=int32)

In [112]:
np.mean(arr)

np.float64(25.28)

In [113]:
np.median(arr)

np.float64(27.0)

In [114]:
np.max(arr)

np.int32(49)

In [115]:
np.min(arr)

np.int32(1)

In [116]:
np.std(arr)

np.float64(14.06277355289489)

In [117]:
np.var(arr)

np.float64(197.7616)

## Boolean indexing

In [121]:
arr = np.random.randint(1,100,100)

In [122]:
arr

array([89, 13, 55,  9, 99, 91, 24, 17, 42, 42, 89, 65,  2, 11, 64, 34, 63,
        4, 56,  1, 12, 86, 71, 10, 52, 27,  5, 18, 58, 97, 46, 64, 65, 54,
       23, 64, 96,  9, 15, 27, 28, 89, 60,  3,  1, 45, 59, 71,  2, 44,  2,
       77, 16, 89, 44, 66, 47, 38,  9, 12,  2, 56, 84, 90, 80, 73, 66, 64,
       90,  4, 52, 40, 29, 10, 15, 97, 79, 56, 10,  2, 25, 18, 68, 20, 28,
       99, 68, 85,  3, 61, 18, 15, 25, 70, 40, 67, 54, 68, 12, 99],
      dtype=int32)

In [123]:
arr[arr>50]

array([89, 55, 99, 91, 89, 65, 64, 63, 56, 86, 71, 52, 58, 97, 64, 65, 54,
       64, 96, 89, 60, 59, 71, 77, 89, 66, 56, 84, 90, 80, 73, 66, 64, 90,
       52, 97, 79, 56, 68, 99, 68, 85, 61, 70, 67, 54, 68, 99],
      dtype=int32)

In [124]:
arr[arr%2==0]

array([24, 42, 42,  2, 64, 34,  4, 56, 12, 86, 10, 52, 18, 58, 46, 64, 54,
       64, 96, 28, 60,  2, 44,  2, 16, 44, 66, 38, 12,  2, 56, 84, 90, 80,
       66, 64, 90,  4, 52, 40, 10, 56, 10,  2, 18, 68, 20, 28, 68, 18, 70,
       40, 54, 68, 12], dtype=int32)

In [125]:
arr[arr%2!=0]

array([89, 13, 55,  9, 99, 91, 17, 89, 65, 11, 63,  1, 71, 27,  5, 97, 65,
       23,  9, 15, 27, 89,  3,  1, 45, 59, 71, 77, 89, 47,  9, 73, 29, 15,
       97, 79, 25, 99, 85,  3, 61, 15, 25, 67, 99], dtype=int32)

In [126]:
arr[arr%5==0]

array([55, 65, 10,  5, 65, 15, 60, 45, 90, 80, 90, 40, 10, 15, 10, 25, 20,
       85, 15, 25, 70, 40], dtype=int32)

In [132]:
arr[arr % 2 == 0] = -1

In [133]:
arr

array([89, 13, 55,  9, 99, 91, -1, 17, -1, -1, 89, 65, -1, 11, -1, -1, 63,
       -1, -1,  1, -1, -1, 71, -1, -1, 27,  5, -1, -1, 97, -1, -1, 65, -1,
       23, -1, -1,  9, 15, 27, -1, 89, -1,  3,  1, 45, 59, 71, -1, -1, -1,
       77, -1, 89, -1, -1, 47, -1,  9, -1, -1, -1, -1, -1, -1, 73, -1, -1,
       -1, -1, -1, -1, 29, -1, 15, 97, 79, -1, -1, -1, 25, -1, -1, -1, -1,
       99, -1, 85,  3, 61, -1, 15, 25, -1, -1, 67, -1, -1, -1, 99],
      dtype=int32)

## broadCasting

In [135]:

#creat 5x5 mat and add 10 to every element, 
#multiply every element by 5,
#square every element 



In [136]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

mat + 10

In [138]:
mat * 5

array([[  5,  10,  15,  20,  25],
       [ 30,  35,  40,  45,  50],
       [ 55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100],
       [105, 110, 115, 120, 125]])

In [139]:
mat ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225],
       [256, 289, 324, 361, 400],
       [441, 484, 529, 576, 625]])

## Aggregation func


In [140]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [151]:
np.sum(mat,axis = 1)

array([ 15,  40,  65,  90, 115])

In [152]:
np.sum(mat,axis = 0)

array([55, 60, 65, 70, 75])

In [157]:
np.argmax(mat.sum(axis=1))

np.int64(4)

In [159]:
np.argmin(np.average(mat,axis=0))

np.int64(0)

## Final Challenge

Create a dataset of marks for 10 students in 5 subjects using NumPy.

Perform all of the following:

Calculate each student's total marks,
Calculate average marks.
Find the topper.
Find the student with the lowest marks.
Display students scoring above 75% average.
Find subject-wise averages.
Identify the highest score in each subject.
Identify the lowest score in each subject.

In [ ]:
marks = np.array([
    [85, 78, 92, 88, 95],
    [67, 74, 70, 72, 80],
    [90, 91, 89, 87, 93],
    [56, 65, 60, 58, 62],
    [77, 81, 79, 84, 86],
    [94, 96, 95, 90, 98],
    [72, 69, 75, 71, 73],
    [88, 85, 90, 86, 89],
    [61, 64, 59, 66, 68],
    [80, 83, 82, 79, 85]
])

In [163]:
np.sum(marks,axis=1)

array([438, 363, 450, 301, 407, 473, 360, 438, 318, 409])

In [164]:
np.average(marks,axis=1)

array([87.6, 72.6, 90. , 60.2, 81.4, 94.6, 72. , 87.6, 63.6, 81.8])

In [166]:
np.argmax(np.average(marks,axis=1))

np.int64(5)

In [167]:
np.argmin(np.sum(marks,axis=1))

np.int64(3)

In [179]:
abv_75 = np.average(marks,axis=1)
abv_75

array([87.6, 72.6, 90. , 60.2, 81.4, 94.6, 72. , 87.6, 63.6, 81.8])

In [181]:
abv_75[abv_75 > 75]

array([87.6, 90. , 81.4, 94.6, 87.6, 81.8])

In [182]:
sub_avg = np.average(marks,axis=0)

In [183]:
sub_avg

array([77. , 78.6, 79.1, 78.1, 82.9])

In [185]:
high_scr_sub = np.max(marks,axis=0)
high_scr_sub

array([94, 96, 95, 90, 98])

In [186]:
low_scr_sub = np.min(marks,axis=0)
low_scr_sub

array([56, 64, 59, 58, 62])